16:28:31 INFO Flight Departure Delays Polynomial Regression Model Log
16:28:32 WARNING Malformed experiment '1'. Detailed error Yaml file 'C:\Users\remsteele\Desktop\WGU_Capstone\D602-Airline-Delay-Prediction\d602-deployment-task-2\mlruns\1\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\remsteele\anaconda3\Lib\site-packages\mlflow\store\tracking\file_store.py", line 328, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\remsteele\anaconda3\Lib\site-packages\mlflow\store\tracking\file_store.py", line 422, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\remsteele\anaconda3\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1368, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\remsteele\anaconda3\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1361, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\remsteele\anaconda3\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file 'C:\Users\remsteele\Desktop\WGU_Capstone\D602-Airline-Delay-Prediction\d602-deployment-task-2\mlruns\1\meta.yaml' does not exist.
16:28:32 INFO Month and year of data: 1 2024
16:28:35 INFO Airport one-hot encoding successful
16:28:35 DEBUG Popen(['git', 'version'], cwd=C:\Users\remsteele\Desktop\WGU_Capstone\D602-Airline-Delay-Prediction\d602-deployment-task-2, universal_newlines=False, shell=None, istream=None)
16:28:35 DEBUG Popen(['git', 'version'], cwd=C:\Users\remsteele\Desktop\WGU_Capstone\D602-Airline-Delay-Prediction\d602-deployment-task-2, universal_newlines=False, shell=None, istream=None)
16:28:36 INFO n=1 alpha=0.0 , MSE = 1.3453e+20
16:28:36 INFO n=1 alpha=0.2 , MSE = 100.78
16:28:36 INFO n=1 alpha=0.4 , MSE = 99.114
16:28:36 INFO n=1 alpha=0.6 , MSE = 97.882
16:28:36 INFO n=1 alpha=0.8 , MSE = 96.926
16:28:36 INFO n=1 alpha=1.0 , MSE = 96.155
16:28:36 INFO n=1 alpha=1.2 , MSE = 95.516
16:28:36 INFO n=1 alpha=1.4 , MSE = 94.974
16:28:37 INFO n=1 alpha=1.6 , MSE = 94.506
16:28:37 INFO n=1 alpha=1.8 , MSE = 94.095
16:28:37 INFO n=1 alpha=2.0 , MSE = 93.731
16:28:37 INFO n=1 alpha=2.2 , MSE = 93.404
16:28:37 INFO n=1 alpha=2.4 , MSE = 93.109
16:28:37 INFO n=1 alpha=2.6 , MSE = 92.84
16:28:37 INFO n=1 alpha=2.8 , MSE = 92.594
16:28:37 INFO n=1 alpha=3.0 , MSE = 92.367
16:28:37 INFO n=1 alpha=3.2 , MSE = 92.157
16:28:37 INFO n=1 alpha=3.4 , MSE = 91.962
16:28:37 INFO n=1 alpha=3.6 , MSE = 91.779
16:28:38 INFO n=1 alpha=3.8 , MSE = 91.608
16:28:38 INFO Training Data Final MSE = 91.61
16:28:38 INFO Model training loop completed with 20 iterations
16:28:38 INFO Export of airport one-hot encoding successful
16:28:38 INFO Wrangling of test data successful
16:28:38 INFO Test Data MSE = 88.19
16:28:38 INFO Predictions using test data successful
16:28:38 INFO Test Data average delay = 9.39 min
16:28:38 INFO Final model export successful
16:29:09 DEBUG Loaded backend module://matplotlib_inline.backend_inline version unknown.
16:29:09 DEBUG Loaded backend module://matplotlib_inline.backend_inline version unknown.
16:29:10 INFO Model performance plot export successful
16:29:14 WARNING Malformed experiment '1'. Detailed error Yaml file 'C:\Users\remsteele\Desktop\WGU_Capstone\D602-Airline-Delay-Prediction\d602-deployment-task-2\mlruns\1\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\remsteele\anaconda3\Lib\site-packages\mlflow\store\tracking\file_store.py", line 328, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\remsteele\anaconda3\Lib\site-packages\mlflow\store\tracking\file_store.py", line 422, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\remsteele\anaconda3\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1368, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\remsteele\anaconda3\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1361, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\remsteele\anaconda3\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file 'C:\Users\remsteele\Desktop\WGU_Capstone\D602-Airline-Delay-Prediction\d602-deployment-task-2\mlruns\1\meta.yaml' does not exist.
16:29:14 WARNING Malformed experiment '1'. Detailed error Yaml file 'C:\Users\remsteele\Desktop\WGU_Capstone\D602-Airline-Delay-Prediction\d602-deployment-task-2\mlruns\1\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\remsteele\anaconda3\Lib\site-packages\mlflow\store\tracking\file_store.py", line 328, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\remsteele\anaconda3\Lib\site-packages\mlflow\store\tracking\file_store.py", line 422, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\remsteele\anaconda3\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1368, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\remsteele\anaconda3\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1361, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\remsteele\anaconda3\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file 'C:\Users\remsteele\Desktop\WGU_Capstone\D602-Airline-Delay-Prediction\d602-deployment-task-2\mlruns\1\meta.yaml' does not exist.
16:29:14 WARNING Malformed experiment '1'. Detailed error Yaml file 'C:\Users\remsteele\Desktop\WGU_Capstone\D602-Airline-Delay-Prediction\d602-deployment-task-2\mlruns\1\meta.yaml' does not exist.
Traceback (most recent call last):
  File "C:\Users\remsteele\anaconda3\Lib\site-packages\mlflow\store\tracking\file_store.py", line 328, in search_experiments
    exp = self._get_experiment(exp_id, view_type)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\remsteele\anaconda3\Lib\site-packages\mlflow\store\tracking\file_store.py", line 422, in _get_experiment
    meta = FileStore._read_yaml(experiment_dir, FileStore.META_DATA_FILE_NAME)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\remsteele\anaconda3\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1368, in _read_yaml
    return _read_helper(root, file_name, attempts_remaining=retries)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\remsteele\anaconda3\Lib\site-packages\mlflow\store\tracking\file_store.py", line 1361, in _read_helper
    result = read_yaml(root, file_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\remsteele\anaconda3\Lib\site-packages\mlflow\utils\file_utils.py", line 310, in read_yaml
    raise MissingConfigException(f"Yaml file '{file_path}' does not exist.")
mlflow.exceptions.MissingConfigException: Yaml file 'C:\Users\remsteele\Desktop\WGU_Capstone\D602-Airline-Delay-Prediction\d602-deployment-task-2\mlruns\1\meta.yaml' does not exist.
